# Generated by Django 5.0.3 on 2024-03-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_movie_release_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
                ('order', models.ManyToManyField(to='home.order')),
            ],
        ),
    ]
