# Generated by Django 5.0.3 on 2024-03-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ManyToManyField(related_name='orders', to='home.order'),
        ),
    ]
