# Generated by Django 5.0.3 on 2024-03-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_invoice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.IntegerField(default=0),
        ),
    ]
