# Generated by Django 5.0.3 on 2024-04-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_monthly_sales'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monthly_Sales',
            new_name='Monthly_Sale',
        ),
    ]
