# Generated by Django 5.0.3 on 2024-04-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_monthly_sales_monthly_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_sale',
            name='movies_rented',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthly_sale',
            name='movies_rented_map',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='monthly_sale',
            name='movies_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthly_sale',
            name='movies_sold_map',
            field=models.JSONField(default=dict),
        ),
    ]
