# Generated by Django 5.0.3 on 2024-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_movies_rented_map_monthly_sale_movies_map_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthly_sale',
            old_name='movies_map',
            new_name='rented_movies',
        ),
        migrations.AddField(
            model_name='monthly_sale',
            name='sold_movies',
            field=models.JSONField(default=dict),
        ),
    ]
